# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'active_storage_validations'
gem 'bootsnap', require: false
gem 'graph_matching'
gem 'graphql'
gem 'graphql-order_by', github: 'mintyfresh/graphql-order_by'
gem 'graphql-rails_logger'
gem 'has_unique_attribute'
gem 'moonfire', github: 'mintyfresh/moonfire'
gem 'oj'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'rails', '~> 7.1'
gem 'scenic'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'where_any'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'method_source'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'annotate'
end

group :test do
  gem 'rspec-rails'
end
